version: "3.3"

volumes:
  postgres-data:
    driver: local
  gems:
    driver: local

services:
  db:
    image: postgres:9.6
    ports:
      - 5433:5432
    volumes:
      - .:/code
      - postgres-data:/var/lib/postgresql/data
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_PASSWORD: P4Ssw0rD!

  web: &app
    image: integrador/makers:development
    command: rails server -p 3000 -b 0.0.0.0
    ports:
      - ${MAKERS_WEB_PORT:-3000}:3000
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: bin/dev-entrypoint
    volumes:
      - .:/code
      - gems:/usr/local/bundle
    working_dir: /code
    tty: false
    stdin_open: true
    environment: &app_environment
      LC_ALL: C.UTF-8
      RAILS_LOG_TO_STDOUT: "true"
      DATABASE_URL: ${DEV_DB_URL:-""}
      RAILS_ENV: ${DEV_RAILS_ENV}
      RACK_ENV: ${DEV_RACK_ENV}
    depends_on:
      - db
  test:
    <<: *app
    command: rspec
    ports:
      - 3001:3001
    environment:
      <<: *app_environment
      DATABASE_URL: ${TEST_DB_URL:-""}
      RAILS_ENV: ${TEST_RAILS_ENV}
      RACK_ENV: ${TEST_RACK_ENV}
      SELENIUM_URL: "http://browser:4444"
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome-debug:3.141.59
    container_name: browser
    platform: linux/amd64
    shm_size: '2gb' 
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=
    volumes:
      - "/dev/shm:/dev/shm"
    ports:
      - "4444:4444"
      - "5900:5900"
